### ISSUE TITLE
nixpkgs 22.05 ???

### ISSUE THREAD

**Issue by hello-smile6** [replit/nixpkgs-replit#67]
When will nixpkgs 22.05 be available?

**Comment by cbrewster** [comment]
Hi! 22.05 is available on Replit now, you can use this by changing the Nix channel in your `.replit` file:

```toml
[nix]
channel = "stable-22_05"
```

Hope this helps!
